name: Append Day Functions to Files

on:
  schedule:
    #- cron: "0 0 * 12 1-31"
    - cron: "31,36 14 * * *"

jobs:
  append_day_functions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set day variable
      run: |
        day=$(date '+%d')
        echo "Day of the month: $day"
        echo "::set-output name=DAY::$day"

    - name: Append functions to days.ts
      run: |
        day=${{ steps.set_day.outputs.DAY }}

        echo "function day_${day}_1(test) {" >> days.ts
        echo "  let input = getInput(${day}, test);" >> days.ts
        echo "  console.log('Some Day ${day}_1 info...', input);" >> days.ts
        echo "  return 'wow';" >> days.ts
        echo "}" >> days.ts

        echo "" >> days.ts

        echo "function day_${day}_2(test) {" >> days.ts
        echo "  let input = getInput(${day}, test);" >> days.ts
        echo "  console.log('Some Day ${day}_2 info...', input);" >> days.ts
        echo "  return 'wow';" >> days.ts
        echo "}" >> days.ts

    - name: Append functions to inputs.ts
      run: |
        day=${{ steps.set_day.outputs.DAY }}

        echo "export function getDay${day}Input(): string {" >> inputs.ts
        echo "  return \`day${day}\`;" >> inputs.ts
        echo "}" >> inputs.ts

        echo "" >> inputs.ts

        echo "export function getDay${day}TestInput(): string {" >> inputs.ts
        echo "  return \`day${day}Test\`;" >> inputs.ts
        echo "}" >> inputs.ts

    - name: Commit and push changes
      run: |
        day=${{ steps.set_day.outputs.DAY }}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add days.ts inputs.ts
        git commit -m "Append functions for day $day"
        git push https://github.com/BenjaminDerProgrammierer/advent-of-code-fw/ HEAD:main
