name: Append Day Functions to Files

on:
  schedule:
    #- cron: "0 0 * 12 1-31"
    - cron: "31,36 14 * * *"

jobs:
  append_day_functions:
    runs-on: ubuntu-latest
    
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write

    steps:
    - uses: actions/checkout@v2
      
    - name: Set day variable
      id: set_day
      run: echo "::set-output name=DAY::$(date '+%d')"

    - name: Append functions to days.ts
      run: |
        day=${{ steps.set_day.outputs.DAY }}

        echo "function day_${day}_1(test) {" >> days.ts
        echo "  let input = getInput(${day}, test);" >> days.ts
        echo "  console.log('Some Day ${day}_1 info...', input);" >> days.ts
        echo "  return 'wow';" >> days.ts
        echo "}" >> days.ts

        echo "" >> days.ts

        echo "function day_${day}_2(test) {" >> days.ts
        echo "  let input = getInput(${day}, test);" >> days.ts
        echo "  console.log('Some Day ${day}_2 info...', input);" >> days.ts
        echo "  return 'wow';" >> days.ts
        echo "}" >> days.ts

    - name: Append functions to inputs.ts
      run: |
        day=${{ steps.set_day.outputs.DAY }}

        echo "export function getDay${day}Input(): string {" >> inputs.ts
        echo "  return \`day${day}\`;" >> inputs.ts
        echo "}" >> inputs.ts

        echo "" >> inputs.ts

        echo "export function getDay${day}TestInput(): string {" >> inputs.ts
        echo "  return \`day${day}Test\`;" >> inputs.ts
        echo "}" >> inputs.ts

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: Init Day ${{ steps.set_day.outputs.DAY }}
        commit_user_name: Day Updater # defaults to "github-actions[bot]"
        commit_user_email: 41898282+my-day-updater@users.noreply.github.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"

    


